### ISSUE TITLE
Add paper 

### ISSUE THREAD

**Issue by 943fansi** [xuhongzuo/DeepOD#16]
周小晖,王意洁,徐鸿祚,刘铭宇.基于融合学习的无监督多维时间序列异常检测[J/OL].计算机研究与发展:1-14.
I am interested with this work; will you add this code in the future?

**Comment by xuhongzuo** [comment]
Thanks for your interest!

The first author is working on releasing the source code of this paper. If you are looking for an anomaly detection model for time-series data, you can find a contemporary work at https://github.com/xuhongzuo/couta.

Cheers!

**Comment by xuhongzuo** [comment]
Thanks for your interest!

The first author of this paper is working on releasing the source code. If you are looking for a time-series anomaly detection model, I may suggest a contemporary work at https://github.com/xuhongzuo/couta.

Cheers!

**Comment by 943fansi** [comment]
@xuhongzuo. Thank you for your recommendation. I am reading this article, and if I have any questions, I will ask them there.

Cheers!
