### ISSUE TITLE
DevNet: reproducing the same results as the paper 

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [xuhongzuo/DeepOD#22]
Hi there,
First of all: thank you very much for this great repo.
I just wanted to ask how could I use your DevNet class to recreate the results that were mentioned in the original paper.

**Comment by xuhongzuo** [comment]
Hi @Aml-Hassan-Abd-El-hamid ,

The official implementation of DevNet uses Keras, and we use PyTorch. It may inevitably lead to slightly different results. Our implementation follows the published paper and also follows the original repo.

Thanks so much for your interest.
