### ISSUE TITLE
dif.py uses deprecated hidden dims syntax

### ISSUE THREAD

**Issue by NAThompson** [xuhongzuo/DeepOD#44]
The constructor for `DeepIsolationForestTS` contains the following line:

https://github.com/xuhongzuo/DeepOD/blob/c2c7566d63bb0beb50ef664498f1d0318dca255a/deepod/models/time_series/dif.py#L27

However, this causes emission of a ginormous number of warnings:

```
Start Training...
  0%|                                                                                              | 0/50 [00:00<?, ?it/s]
$VIRTUAL_ENV/lib/python3.9/site-packages/deepod/core/networks/network_utility.py:23: UserWarning: use the first hidden num, the rest hidden numbers are deprecated
  warnings.warn('use the first hidden num, '
  2%|█▋
```

Fix is very easy of course, just change `hidden_dims='100,50'` to `hidden_dims=100`.

**Comment by xuhongzuo** [comment]
Thanks so much. I have just merged the PR.
