### ISSUE TITLE
Unable to Import Module 'deepod.metrics.affiliation' in Testbed_unsupervised_tsad.py

### ISSUE THREAD

**Issue by makinno** [xuhongzuo/DeepOD#48]
**Issue Description:**
When attempting to run the **testbed_unsupervised_tsad.py** script from the DeepOD library's Testbed, I encountered an **ImportError** related to the module **'deepod.metrics.affiliation'**. 

**Error Traceback:**
```
Traceback (most recent call last):
  File "E:\AD\DeepOD\testbed\testbed_unsupervised_tsad.py", line 16, in <module>
    from deepod.metrics import ts_metrics, point_adjustment
  ...
  File "D:\ruanjian\anaconda\envs\DeepOD\lib\site-packages\deepod\metrics\_anomaly_detection.py", line 3, in <module>
    from deepod.metrics.affiliation.generics import convert_vector_to_events
ModuleNotFoundError: No module named 'deepod.metrics.affiliation'
```

**Steps to Reproduce:**

1. Clone the DeepOD repository.
2. Follow the Testbed documentation for setting up the environment.
3. Execute the testbed_unsupervised_tsad.py script with the provided example command.

**Additional Information:**
DeepOD version: 0.4.1
Python version: 3.9
Operating System: Windows 11 Pro

I would appreciate any guidance or suggestions to resolve this issue and successfully run the **testbed_unsupervised_tsad.py** script.

**Comment by xuhongzuo** [comment]
Hi @makinno, 
I am sorry for this issue. I just updated the repository.
In `testbed_unsupervised_tsad.py`, the parent path is added. 
```Python
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

```

If you have installed Deepod via pip, you may need to uninstall it first. You can directly clone the whole project and run the testbed.

**Comment by makinno** [comment]
Hi @xuhongzuo,

Thank you for your prompt response and the update to the repository. I appreciate your efforts in addressing the issue. I followed the suggested solution, but the issue persists. Is there anything else I should consider or any additional steps to take in order to resolve this problem?

Your continued assistance is highly appreciated.

**Comment by xuhongzuo** [comment]
you should first uninstall the DeepOD via pip 
```
pip uninstall deepod
```

Then, you can run the testbed
![image](https://github.com/xuhongzuo/DeepOD/assets/37388323/48605ac1-e323-4499-b11b-c67a49da5bc2)

**Comment by makinno** [comment]
Despite uninstalling DeepOD via pip as suggested and following your instructions, the ImportError related to 'deepod.metrics.affiliation' persists. Here are the screenshots for reference. 
![DeepOD 2023-12-12 112136](https://github.com/xuhongzuo/DeepOD/assets/84600438/09c05b43-4891-4275-86b4-37c003deae1a)
![Deep OD 2023-12-12 112314](https://github.com/xuhongzuo/DeepOD/assets/84600438/57957bea-2674-44f0-8ea8-c59be8951c18)
![DeepOD 2023-12-12 112359](https://github.com/xuhongzuo/DeepOD/assets/84600438/1fd37cb6-91f9-444e-b445-6fe348e22c33)

**Comment by xuhongzuo** [comment]
I updated several hours ago by adding __init__.py into deepod/metrics/affiliation 

I am not sure whether you use the latest version. 

I just tried the testbed by directly cloning from the GitHub. 

Could you please follow the steps below and try again?



```
git clone https://github.com/xuhongzuo/DeepOD.git
cd DeepOD

```

(Please do not install DeepOD via pip now. )


modify the data folder in the testbed


```
python testbed_unsupervised_tsad.py
```

**Comment by makinno** [comment]
Thank you for the update. I've identified that the missing 'affiliation' and 'vus' submodules in the metrics directory of the DeepOD installation (`...\site-packages\deepod\metrics`) were causing the ModuleNotFoundError. I added them manually, resolving the issue. I'll uninstall DeepOD, clone the latest version, and follow your steps to ensure a clean installation. I appreciate your assistance and time.

**Comment by xuhongzuo** [comment]
If the site-packages does not have the 'affilation' and 'vus' submodules, your installed deepod is not the latest version. 
You should try to use `pip install .` to install the latest version.

**Comment by makinno** [comment]
I have successfully cloned the latest version of DeepOD, and the ModuleNotFoundError has been resolved. Regarding the execution of 'testbed_unsupervised_tsad.py' with custom CSV datasets, is there specific documentation available to guide me through this process? Your guidance has been invaluable, and I eagerly anticipate exploring the capabilities of DeepOD further. Thank you

**Comment by xuhongzuo** [comment]
Thank you for raising this issue!

We have not had specific documentation of using custom CSV datasets in the testbed for now. I will add one soon. If you are interested, we really appreciate it if you can contribute to our documentation.
